<%@ taglib uri="jakarta.tags.core" prefix="c" %>
<%@ include file="_header.jspf" %>

<section class="card">
    <h2>Expiry Alerts</h2>
    <p>Alerts are generated by a chain: Expiry check, urgency flag, chef notify, manager escalate.</p>
    <table>
        <thead>
        <tr>
            <th>Ingredient</th>
            <th>Days to Expiry</th>
            <th>Urgent</th>
            <th>Events</th>
        </tr>
        </thead>
        <tbody>
        <c:forEach var="alert" items="${alerts}">
            <tr>
                <td>${alert.ingredient.name}</td>
                <td>${alert.daysUntilExpiry}</td>
                <td>${alert.urgent}</td>
                <td>
                    <c:forEach var="event" items="${alert.events}">
                        <div>${event}</div>
                    </c:forEach>
                </td>
            </tr>
        </c:forEach>
        </tbody>
    </table>
</section>

<%@ include file="_footer.jspf" %>
